platform :ios, '12.1'

target 'EEMI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EEMI
  pod 'SwiftLint'

  target 'EEMITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EEMIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
